bipy.core.exception.IDMismatchError
===================================

.. currentmodule:: bipy.core.exception

.. autoexception:: IDMismatchError